SFX:
; entries correspond to SFX_* constants
	dba Sfx_ObtainItem
	dba Sfx_Entrustment
	dba Sfx_GoodDexRating
	dba Sfx_NewLevel
	dba Sfx_Evolution
	dba Sfx_ObtainKeyItem
	dba Sfx_EggHatched
	dba Sfx_CaughtNewMon
	dba Sfx_PokemonAssembled
	dba Sfx_PokedexReward
	dba Sfx_TMHM
	dba Sfx_Badge
	dba Sfx_BadDexRating
	dba Sfx_CompleteDex
	dba Sfx_GameCornerWin
	dba Sfx_EmailAddressRegistered
	dba Sfx_PokeBall
	dba Sfx_Prize
; leftover from G/S
	dba Sfx_3rdPlace
	dba Sfx_GetEgg
	dba Sfx_MoveDeleted
	dba Sfx_QuitSlots
	dba Sfx_KeepAtIt
	dba Sfx_NotTooShabby
	dba Sfx_AlmostFinished
; normal SFX
	dba Sfx_PokeballsPlacedOnTable
	dba Sfx_Potion
	dba Sfx_FullHeal
	dba Sfx_Menu
	dba Sfx_ReadText
	dba Sfx_ReadText
	dba Sfx_Poison
	dba Sfx_GotSafariBalls
	dba Sfx_BootPc
	dba Sfx_ShutDownPc
	dba Sfx_ChoosePcOption
	dba Sfx_EscapeRope
	dba Sfx_PushButton
	dba Sfx_SecondPartOfItemfinder
	dba Sfx_WarpTo
	dba Sfx_WarpFrom
	dba Sfx_ChangeDexMode
	dba Sfx_JumpOverLedge
	dba Sfx_GrassRustle
	dba Sfx_Fly
	dba Sfx_Wrong
	dba Sfx_Squeak
	dba Sfx_Strength
	dba Sfx_Boat
	dba Sfx_WallOpen
	dba Sfx_PlacePuzzlePieceDown
	dba Sfx_EnterDoor
	dba Sfx_SwitchPokemon
	dba Sfx_Tally
	dba Sfx_Transaction
	dba Sfx_ExitBuilding
	dba Sfx_Bump
	dba Sfx_Save
	dba Sfx_Pokeflute
	dba Sfx_ElevatorEnd
	dba Sfx_ThrowBall
	dba Sfx_BallPoof
	dba Sfx_Faint
	dba Sfx_Run
	dba Sfx_SlotMachineStart
	dba Sfx_Peck
	dba Sfx_Kinesis
	dba Sfx_Lick
	dba Sfx_Pound
	dba Sfx_MovePuzzlePiece
	dba Sfx_CometPunch
	dba Sfx_MegaPunch
	dba Sfx_Scratch
	dba Sfx_Vicegrip
	dba Sfx_RazorWind
	dba Sfx_Cut
	dba Sfx_WingAttack
	dba Sfx_Whirlwind
	dba Sfx_Bind
	dba Sfx_VineWhip
	dba Sfx_DoubleKick
	dba Sfx_MegaKick
	dba Sfx_Headbutt
	dba Sfx_HornAttack
	dba Sfx_Tackle
	dba Sfx_PoisonSting
	dba Sfx_Powder
	dba Sfx_Doubleslap
	dba Sfx_Bite
	dba Sfx_JumpKick
	dba Sfx_Stomp
	dba Sfx_TailWhip
	dba Sfx_Burn
	dba Sfx_Submission
	dba Sfx_WaterGun
	dba Sfx_SwordsDance
	dba Sfx_Thunder
	dba Sfx_Supersonic
	dba Sfx_Leer
	dba Sfx_Ember
	dba Sfx_Bubblebeam
	dba Sfx_HydroPump
	dba Sfx_Surf
	dba Sfx_Psybeam
	dba Sfx_Charge
	dba Sfx_Thundershock
	dba Sfx_Psychic
	dba Sfx_Screech
	dba Sfx_BoneClub
	dba Sfx_Sharpen
	dba Sfx_EggBomb
	dba Sfx_Sing
	dba Sfx_HyperBeam
	dba Sfx_Shine
	dba Sfx_Unknown72
	dba Sfx_RBDemoLunge
	dba Sfx_Unknown74
	dba Sfx_SwitchPockets
	dba Sfx_RBVersionNameEntrance
	dba Sfx_Burn
	dba Sfx_TitleScreenEntrance
	dba Sfx_RBYSlotStop
	dba Sfx_GetCoinFromSlots
	dba Sfx_PayDayGS
	dba Sfx_Metronome
	dba Sfx_Call
	dba Sfx_HangUp
	dba Sfx_NoSignal
	dba Sfx_Sandstorm
	dba Sfx_Elevator
	dba Sfx_Protect
	dba Sfx_Sketch
	dba Sfx_RainDance
	dba Sfx_Aeroblast
	dba Sfx_Spark
	dba Sfx_Curse
	dba Sfx_Rage
	dba Sfx_Thief
	dba Sfx_Thief2
	dba Sfx_SpiderWeb
	dba Sfx_MindReader
	dba Sfx_Nightmare
	dba Sfx_Snore
	dba Sfx_SweetKiss
	dba Sfx_SweetKiss2
	dba Sfx_BellyDrum
	dba Sfx_Toxic
	dba Sfx_SludgeBomb
	dba Sfx_Foresight
	dba Sfx_Spite
	dba Sfx_Outrage
	dba Sfx_PerishSong
	dba Sfx_GigaDrain
	dba Sfx_Attract
	dba Sfx_Kinesis2
	dba Sfx_ZapCannon
	dba Sfx_MeanLook
	dba Sfx_HealBell
	dba Sfx_Return
	dba Sfx_ExpBar
	dba Sfx_MilkDrink
	dba Sfx_Present
	dba Sfx_MorningSun
	dba Sfx_EggCrack
	dba Sfx_Evolved
	dba Sfx_MasterBall
	dba Sfx_EggHatch
	dba Sfx_GsIntroCharizardFireball
	dba Sfx_GsIntroPokemonAppears
	dba Sfx_Flash
	dba Sfx_GameFreakLogoGs
	dba Sfx_NotVeryEffective
	dba Sfx_Damage
	dba Sfx_SuperEffective
	dba Sfx_BallBounce
	dba Sfx_Moonlight
	dba Sfx_Encore
	dba Sfx_BeatUp
	dba Sfx_BatonPass
	dba Sfx_BallWobble
	dba Sfx_SweetScent
	dba Sfx_SweetScent2
	dba Sfx_HitEndOfExpBar
	dba Sfx_GiveTrademon
	dba Sfx_GetTrademon
	dba Sfx_TrainArrived
	dba Sfx_StopSlot
	dba Sfx_2Boops
; crystal sfx, imported
	dba Sfx_GlassTing
	dba Sfx_GlassTing2
	dba Sfx_IntroUnown1
	dba Sfx_IntroUnown2
	dba Sfx_IntroUnown3
	dba Sfx_DittoPopUp
	dba Sfx_DittoTransform
	dba Sfx_IntroSuicune1
	dba Sfx_IntroPichu
	dba Sfx_IntroSuicune2
	dba Sfx_IntroSuicune3
	dba Sfx_DittoBounce
	dba Sfx_IntroSuicune4
	dba Sfx_GameFreakPresents
	dba Sfx_Tingle
	dba Sfx_IntroWhoosh
	dba Sfx_TwoPcBeeps
	dba Sfx_4NoteDitty
	dba Sfx_Twinkle
; imported
	dba Sfx_ShootingStar
	dba Sfx_RBYSing
	dba Sfx_PokefluteHome
	dba Sfx_LockOn
	dba Sfx_Flail
	dba Sfx_BallClose
	dba Sfx_InLove
	dba Sfx_Amnesia
	dba Sfx_ExpBarFilled
	dba Sfx_Mimic1
	dba Sfx_Mimic2
	dba Sfx_Mimic3
	dba Sfx_Mimic4
	dba Sfx_Mimic5
	dba Sfx_Mimic6
	dba Sfx_Mimic7
	dba Sfx_BallShake
	dba Sfx_EggRoll
	dba Sfx_Smokescreen
	dba Sfx_Spikes1
	dba Sfx_Spikes2
	dba Sfx_Recover
	dba Sfx_PayDay
	dba Sfx_PokefluteNight
	dba Sfx_PokefluteDungeon
